export const productThumbnails: Record<string, string> = {
  '/products/cantilever-walls': '/images/products/retaining-walls/wccp-retaining-walls-a-wall-732x1024.jpg',
  '/products/cattle-cubicles': '/images/products/cubicles/wccp-cubicles-portable-cubicles-1024x768.jpg',
  '/products/clean-rooms': '/images/products/clean-rooms.jpg',
  '/products/cubicle-end-walls': '/images/products/cubicles/wccp-cubicles-cubicle-trough-slider-1-1024x438.jpg',
  '/products/culverts': '/images/products/culverts/wccp-culverts-20240308-121028-reduced-1024x768.jpg',
  '/products/feed-troughs': '/images/products/feed-troughs/wccp-feed-troughs-j-shape-single-sided-concrete-feed-trough.jpg',
  '/products/footbaths': '/images/products/home/wccp-home-footbath-at-bath-and-west-show-scaled.jpg',
  '/products/heelstone-coping': '/images/products/cubicles/wccp-cubicles-heel-stone-coping.jpg',
  '/products/interlocking-blocks': '/images/products/betonblocks/wccp-betonblocks-160-80-80-45-voorbeeld-beton-legoblock.jpg',
  '/products/king-post-walls': '/images/products/retaining-walls/wccp-retaining-walls-l-t-wall-1024x732.jpg',
  '/products/l-blocks': '/images/products/home/wccp-home-free-standing-wall-section.jpg',
  '/products/milking-robot-bases': '/images/products/lely-milking-robot-bases/wccp-lely-milking-robot-bases-lely-a4-sump-base-and-surround.png',
  '/products/padstones': '/images/products/home/wccp-home-padstones.jpg',
  '/products/prestressed-panels': '/images/products/concrete-panels/wccp-concrete-panels-prestressed-concrete-panels.jpg',
  '/products/retaining-walls': '/images/products/retaining-walls/wccp-retaining-walls-l-t-wall-1024x732.jpg',
  '/products/sand-channels': '/images/products/slurry-handling/wccp-slurry-handling-image-of-v-sand-slurry-channel.jpg',
  '/products/silage-clamp-walls': '/images/products/concrete-panels/wccp-concrete-panels-prestressed-concrete-panels.jpg',
  '/products/slurry-channels': '/images/products/slurry-handling/wccp-slurry-handling-channel.jpg',
  '/products/slurry-storage': '/images/products/slurry-handling/wccp-slurry-handling-shallow-v-channel.jpg',
  '/products/vehicle-pits': '/images/products/automotive-work-pit/wccp-automotive-work-pit-auto-pit-1-sqr-1-1024x1024.jpg',
  '/products/water-troughs': '/images/products/water-troughs/wccp-water-troughs-500-gallon-crop1-1024x731.jpg',
};
